### ISSUE TITLE
拼写错误

### ISSUE THREAD

**Issue by anlia260** [gomeplusFED/blog#9]
基本实现的第一个例子

document.getElementsById("")  =>  document.getElementById("")

**Comment by luoye-fe** [comment]
哪篇文章呢？

**Comment by anlia260** [comment]
@luoye-fe ,很不好意思，忘记告诉你[地址](https://github.com/gomeplusFED/blog/blame/b452c5f33a16126e5d8870a202bf2a886bc68612/2016-04/do-you-really-understand-how-to-write-a-countdown-by-javascript.md#L18)了。

**Comment by luoye-fe** [comment]
@anlia260 更改了，感谢
